version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: aws-pricing-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=aws-pricing-tool
    networks:
      - aws-pricing-network
    restart: unless-stopped

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aws-pricing-backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/aws-pricing-tool
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    networks:
      - aws-pricing-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aws-pricing-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - aws-pricing-network
    restart: unless-stopped

# Volumes
volumes:
  mongodb_data:
    driver: local

# Networks
networks:
  aws-pricing-network:
    driver: bridge
