apiVersion: v1
kind: Secret
metadata:
  name: aws-pricing-secrets
  namespace: aws-pricing-tool
type: Opaque
data:
  # These are placeholders - replace with actual base64-encoded values
  AWS_ACCESS_KEY_ID: "UkVQTEFDRV9XSVRIX0FDVFVBTF9LRVk="
  AWS_SECRET_ACCESS_KEY: "UkVQTEFDRV9XSVRIX0FDVFVBTF9TRUNSRVRfS0VZ="
  SMTP_USER: "dGVzdEBleGFtcGxlLmNvbQ=="
  SMTP_PASS: "dGVzdF9wYXNzd29yZA=="
